# Generated by Django 4.2 on 2023-08-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactenquiry',
            old_name='massege',
            new_name='messege',
        ),
    ]
