# Generated by Django 4.2 on 2023-08-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='id',
        ),
        migrations.AddField(
            model_name='services',
            name='ContactNumber',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='services',
            name='labour_id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
