# Generated by Django 4.2 on 2023-09-11 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=12)),
                ('common_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paymentapp.commonkey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Pune', 'Pune'), ('Ahmedabad', 'Ahmedabad'), ('Jaipur', 'Jaipur'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Nagpur', 'Nagpur'), ('Patna', 'Patna'), ('Indore', 'Indore'), ('Thane', 'Thane'), ('Bhopal', 'Bhopal'), ('Visakhapatnam', 'Visakhapatnam'), ('Vadodara', 'Vadodara'), ('Ludhiana', 'Ludhiana'), ('Agra', 'Agra'), ('Nashik', 'Nashik'), ('Ranchi', 'Ranchi'), ('Varanasi', 'Varanasi'), ('Srinagar', 'Srinagar'), ('Amritsar', 'Amritsar'), ('Coimbatore', 'Coimbatore'), ('Madurai', 'Madurai'), ('Vijayawada', 'Vijayawada'), ('Jodhpur', 'Jodhpur'), ('Raipur', 'Raipur'), ('Guwahati', 'Guwahati'), ('Chandigarh', 'Chandigarh'), ('Kochi', 'Kochi'), ('Bhubaneswar', 'Bhubaneswar'), ('Salem', 'Salem'), ('Guntur', 'Guntur'), ('Jammu', 'Jammu'), ('Mangalore', 'Mangalore'), ('Kozhikode', 'Kozhikode'), ('Kurnool', 'Kurnool'), ('Vellore', 'Vellore'), ('Rajahmundry', 'Rajahmundry'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Bhagalpur', 'Bhagalpur'), ('Warangal', 'Warangal'), ('Durgapur', 'Durgapur'), ('Asansol', 'Asansol'), ('Nanded', 'Nanded'), ('Kolhapur', 'Kolhapur'), ('Ajmer', 'Ajmer'), ('Akola', 'Akola'), ('Jalgaon', 'Jalgaon'), ('Udaipur', 'Udaipur'), ('Tirupur', 'Tirupur'), ('Davanagere', 'Davanagere'), ('Kozhikode', 'Kozhikode'), ('Kollam', 'Kollam'), ('Bhavnagar', 'Bhavnagar'), ('Dehradun', 'Dehradun'), ('Durgapur', 'Durgapur'), ('Nashik', 'Nashik'), ('Kollam', 'Kollam'), ('Dhanbad', 'Dhanbad'), ('Amravati', 'Amravati'), ('Noida', 'Noida'), ('Jamshedpur', 'Jamshedpur'), ('Bhilai', 'Bhilai'), ('Cuttack', 'Cuttack'), ('Firozpur', 'Firozpur'), ('Nellore', 'Nellore'), ('Jhansi', 'Jhansi'), ('Ulhasnagar', 'Ulhasnagar'), ('Jammu', 'Jammu'), ('Sangli-Miraj & Kupwad', 'Sangli-Miraj & Kupwad'), ('Mangalore', 'Mangalore'), ('Erode', 'Erode'), ('Belgaum', 'Belgaum'), ('Ambattur', 'Ambattur'), ('Tirunelveli', 'Tirunelveli'), ('Malegaon', 'Malegaon'), ('Gaya', 'Gaya'), ('Jalgaon', 'Jalgaon'), ('Udaipur', 'Udaipur'), ('Maheshtala', 'Maheshtala'), ('Tirupur', 'Tirupur'), ('Davanagere', 'Davanagere'), ('Kozhikode', 'Kozhikode'), ('Kurnool', 'Kurnool'), ('Vellore', 'Vellore'), ('Rajahmundry', 'Rajahmundry'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Bhagalpur', 'Bhagalpur'), ('Warangal', 'Warangal'), ('Durgapur', 'Durgapur'), ('Asansol', 'Asansol'), ('Nanded', 'Nanded'), ('Kolhapur', 'Kolhapur'), ('Ajmer', 'Ajmer'), ('Akola', 'Akola'), ('Jalgaon', 'Jalgaon'), ('Ujjain', 'Ujjain'), ('Loni', 'Loni'), ('Siliguri', 'Siliguri'), ('Jhansi', 'Jhansi'), ('Ulhasnagar', 'Ulhasnagar'), ('Jammu', 'Jammu'), ('Sangli-Miraj & Kupwad', 'Sangli-Miraj & Kupwad'), ('Mangalore', 'Mangalore'), ('Erode', 'Erode'), ('Belgaum', 'Belgaum'), ('Ambattur', 'Ambattur'), ('Tirunelveli', 'Tirunelveli'), ('Malegaon', 'Malegaon'), ('Gaya', 'Gaya'), ('Jalgaon', 'Jalgaon'), ('Udaipur', 'Udaipur'), ('Maheshtala', 'Maheshtala'), ('Tirupur', 'Tirupur'), ('Davanagere', 'Davanagere'), ('Kozhikode', 'Kozhikode'), ('Akola', 'Akola'), ('Kurnool', 'Kurnool')], max_length=50)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=50)),
                ('zip', models.CharField(max_length=6)),
                ('common_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paymentapp.commonkey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aboutyou',
            fields=[
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('address_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_you', to='paymentapp.address')),
                ('common_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paymentapp.commonkey')),
                ('contact_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_you', to='paymentapp.contactdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
