# Generated by Django 4.2 on 2023-09-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_alter_address_city_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutyou',
            name='id',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='id',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
        ),
    ]
