# Generated by Django 5.0.7 on 2024-09-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='fname',
            field=models.CharField(default='xyz', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='lname',
            field=models.CharField(default='xyz', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='pass1',
            field=models.CharField(default='1234', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='pass2',
            field=models.CharField(default='1234', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default='xyz@#123', max_length=100),
        ),
    ]
